baseURL = 'https://blog.oxuniliberals.com/'
languageCode = 'en-gb'
title = 'OSLA - Blog'
theme = 'lightbi-hugo'
relativeURLs = true

[Params]
  customCSS = ["css/custom.css"]
  lunrSearch = true
  mainSections = ["blog"]

[Params.Author]
    name = "The Oxford Students Liberal Association (OSLA) - Liberal Since 1913"
    website = "https://www.oxuniliberals.com/"


[[menu.main]]
    name = "Main"
    url = "https://www.oxuniliberals.com/"
    weight = 3

[[menu.main]]
    name = "Submit Article"
    url = "https://oxuniliberals.com/submit-article"
    weight = 30

[[menu.main]]
    name = "Term tags"
    url = "/tags/"
    weight = 3

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "JSON"]
  
